// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iwecygcpkwbkwgqkfbdn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3ZWN5Z2Nwa3dia3dncWtmYmRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY1OTA3MTcsImV4cCI6MjA1MjE2NjcxN30.cCW2mWNbfztvEe8UrWorpcd5icO8vNS34swdQbuMoJg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);